### ISSUE TITLE
Undeclared prerequisite Test2::V0

### ISSUE THREAD

**Issue by andk** [rabbiveesh/mojo-jwt-google#1]
As per subject.
Place of use statement: https://metacpan.org/source/VEESH/Mojo-JWT-Google-0.10/t/01_basic.t#L3
Sample fail report: http://www.cpantesters.org/cpan/report/113214855

HTH && Thanks,

**Comment by rabbiveesh** [comment]
Thanks, I actually saw that test report on my CPANTS feed and it's already fixed in 0.11
